<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>icon\app_crystal_warm.ico</ApplicationIcon>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <PublishAot>true</PublishAot>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <NoWarn>$(NoWarn);IL3053</NoWarn>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="icon\app_icon_crystal_warm.png" />
    <AvaloniaResource Include="Assets\Fonts\*.ttf" />
    <None Update="Assets\Fonts\LICENSE-*.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="SuperLightLogger" Version="1.0.16" />
    <PackageReference Include="Velopack" Version="1.2.0" />
    <PackageReference Include="VelopackUpdateDialog.Avalonia" Version="1.0.16" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Velopack" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Fumilume.Tests" />
  </ItemGroup>
</Project>
